-- Create point_settings table
CREATE TABLE point_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  outlet_id BIGINT REFERENCES outlets(id) ON DELETE CASCADE,
  staff_email TEXT,
  enable_points BOOLEAN DEFAULT true,
  points_value BIGINT DEFAULT 1000,
  points_base_type TEXT DEFAULT '10000',
  points_base_custom BIGINT DEFAULT 5000,
  points_earn_rate BIGINT DEFAULT 1,
  max_points_per_transaction BIGINT DEFAULT 1000,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(outlet_id, staff_email) -- Ensure only one setting per outlet + staff combination
);

-- Note for Unique constraint:
-- Since outlet_id and staff_email can be null to represent "All Outlets" or "All Staff",
-- we might need to be careful. In PostgreSQL, NULL != NULL.
-- For a robust approach, we can use coalesce or partial indexes, but in our case,
-- we'll rely on the application logic to ensure we upsert correctly, or we use unique indexes with coalesce.

CREATE UNIQUE INDEX idx_point_settings_unique_target 
ON point_settings (
  COALESCE(outlet_id, -1), 
  COALESCE(staff_email, 'ALL_STAFF')
);

-- RLS (Row Level Security)
ALTER TABLE point_settings ENABLE ROW LEVEL SECURITY;

-- Allow all authenticated users to read point_settings (or you can restrict to admins)
CREATE POLICY "Enable read access for all users" ON point_settings
  FOR SELECT USING (true);

-- Allow admins/owners to insert/update/delete point_settings
CREATE POLICY "Enable insert for authenticated users" ON point_settings
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users" ON point_settings
  FOR UPDATE USING (true);

CREATE POLICY "Enable delete for authenticated users" ON point_settings
  FOR DELETE USING (true);

-- Grant privileges to roles to prevent 401 Unauthorized
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE point_settings TO anon, authenticated;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE point_settings_id_seq TO anon, authenticated;
