-- Migration: Create expenses table
-- Description: Table for tracking store expenses

-- Create expenses table
CREATE TABLE IF NOT EXISTS expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category VARCHAR(50) NOT NULL,
  description TEXT NOT NULL,
  amount DECIMAL(12, 2) NOT NULL,
  date DATE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add comments
COMMENT ON TABLE expenses IS 'Table for tracking store expenses';
COMMENT ON COLUMN expenses.id IS 'Primary key';
COMMENT ON COLUMN expenses.category IS 'Expense category (operational, inventory, utilities, maintenance, marketing, salary, rent, transport, other)';
COMMENT ON COLUMN expenses.description IS 'Expense description';
COMMENT ON COLUMN expenses.amount IS 'Expense amount in IDR';
COMMENT ON COLUMN expenses.date IS 'Expense date';
COMMENT ON COLUMN expenses.created_at IS 'Record creation timestamp';

-- Insert sample data (optional)
-- INSERT INTO expenses (category, description, amount, date) VALUES
-- ('operational', 'Contoh Pengeluaran', 50000, CURRENT_DATE);
