-- ==========================================
-- Migration for Discount & Tax Settings
-- ==========================================

-- 1. Create discount_categories table (Global)
CREATE TABLE discount_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  note TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert Default Discount Categories
INSERT INTO discount_categories (note) VALUES
  ('Promo Member'),
  ('Diskon Produk'),
  ('Voucher Toko'),
  ('Promo Musiman'),
  ('Komplain Pelanggan')
ON CONFLICT (note) DO NOTHING;

-- RLS for discount_categories
ALTER TABLE discount_categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users on discount_categories" ON discount_categories
  FOR SELECT USING (true);

CREATE POLICY "Enable insert for authenticated users on discount_categories" ON discount_categories
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users on discount_categories" ON discount_categories
  FOR UPDATE USING (true);

CREATE POLICY "Enable delete for authenticated users on discount_categories" ON discount_categories
  FOR DELETE USING (true);

-- 2. Create discount_settings table (Per Outlet & Kasir)
CREATE TABLE discount_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  outlet_id BIGINT REFERENCES outlets(id) ON DELETE CASCADE,
  staff_email TEXT,
  enable_discount BOOLEAN DEFAULT true,
  default_discount_price NUMERIC DEFAULT 0,
  enable_ppn BOOLEAN DEFAULT true,
  ppn_percentage NUMERIC DEFAULT 11,
  allowed_promos JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(outlet_id, staff_email)
);

-- Create unique index to handle NULL values for "All Outlets" and "All Staff"
CREATE UNIQUE INDEX idx_discount_settings_unique_target 
ON discount_settings (
  COALESCE(outlet_id, -1), 
  COALESCE(staff_email, 'ALL_STAFF')
);

-- RLS for discount_settings
ALTER TABLE discount_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users on discount_settings" ON discount_settings
  FOR SELECT USING (true);

CREATE POLICY "Enable insert for authenticated users on discount_settings" ON discount_settings
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users on discount_settings" ON discount_settings
  FOR UPDATE USING (true);

CREATE POLICY "Enable delete for authenticated users on discount_settings" ON discount_settings
  FOR DELETE USING (true);

-- Grant privileges
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE discount_categories TO anon, authenticated;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE discount_categories_id_seq TO anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE discount_settings TO anon, authenticated;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE discount_settings_id_seq TO anon, authenticated;
