


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."is_admin"() RETURNS boolean
    LANGUAGE "sql" STABLE SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
  SELECT COALESCE(lower(auth.jwt() -> 'user_metadata' ->> 'role') = 'admin', false)
  OR lower(auth.jwt() ->> 'email') = 'sbagiamu.pos@gmail.com';
$$;


ALTER FUNCTION "public"."is_admin"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."set_owner_id"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
BEGIN
  IF NEW.owner_id IS NULL THEN NEW.owner_id := auth.uid(); END IF;
  RETURN NEW;
END; $$;


ALTER FUNCTION "public"."set_owner_id"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."update_outlets_updated_at"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."update_outlets_updated_at"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."update_updated_at_column"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."update_updated_at_column"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."app_config" (
    "id" integer NOT NULL,
    "key" "text" NOT NULL,
    "value" "text" NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."app_config" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."app_config_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."app_config_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."app_config_id_seq" OWNED BY "public"."app_config"."id";



CREATE TABLE IF NOT EXISTS "public"."categories" (
    "id" bigint NOT NULL,
    "name" character varying(255) NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "owner_id" "uuid",
    "allowed_outlets" "jsonb" DEFAULT '["all"]'::"jsonb"
);


ALTER TABLE "public"."categories" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."categories_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."categories_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."categories_id_seq" OWNED BY "public"."categories"."id";



CREATE TABLE IF NOT EXISTS "public"."customers" (
    "id" bigint NOT NULL,
    "name" character varying(255) NOT NULL,
    "phone" character varying(50),
    "membership_type" character varying(50) DEFAULT 'regular'::character varying,
    "points" integer DEFAULT 0,
    "total_spent" numeric(12,2) DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "owner_id" "uuid",
    "outlet_id" integer
);


ALTER TABLE "public"."customers" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."customers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."customers_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."customers_id_seq" OWNED BY "public"."customers"."id";



CREATE TABLE IF NOT EXISTS "public"."discount_categories" (
    "id" bigint NOT NULL,
    "note" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."discount_categories" OWNER TO "postgres";


ALTER TABLE "public"."discount_categories" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."discount_categories_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."discount_settings" (
    "id" bigint NOT NULL,
    "outlet_id" bigint,
    "staff_email" "text",
    "enable_discount" boolean DEFAULT true,
    "default_discount_price" numeric DEFAULT 0,
    "enable_ppn" boolean DEFAULT true,
    "ppn_percentage" numeric DEFAULT 11,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "allowed_promos" "jsonb" DEFAULT '[]'::"jsonb"
);


ALTER TABLE "public"."discount_settings" OWNER TO "postgres";


ALTER TABLE "public"."discount_settings" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."discount_settings_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."expense_categories" (
    "id" character varying(255) NOT NULL,
    "name" character varying(255) NOT NULL,
    "color" character varying(50) DEFAULT 'blue'::character varying,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."expense_categories" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."expenses" (
    "id" bigint NOT NULL,
    "category" character varying(50) NOT NULL,
    "description" "text" NOT NULL,
    "amount" numeric(20,2) NOT NULL,
    "date" "date" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "owner_id" "uuid",
    "outlet_id" integer,
    "supplier" "text",
    "image_url" "text"
);


ALTER TABLE "public"."expenses" OWNER TO "postgres";


COMMENT ON COLUMN "public"."expenses"."supplier" IS 'The supplier or recipient of the payment';



COMMENT ON COLUMN "public"."expenses"."image_url" IS 'URL of the uploaded receipt image';



ALTER TABLE "public"."expenses" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."expenses_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."outlets" (
    "id" bigint NOT NULL,
    "name" character varying(255) NOT NULL,
    "address" "text",
    "phone" character varying(50),
    "is_active" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "store_name" "text",
    "footer_message" "text",
    "footer_message2" "text",
    "footer_message3" "text"
);


ALTER TABLE "public"."outlets" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."outlets_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."outlets_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."outlets_id_seq" OWNED BY "public"."outlets"."id";



CREATE TABLE IF NOT EXISTS "public"."point_settings" (
    "id" bigint NOT NULL,
    "outlet_id" bigint,
    "staff_email" "text",
    "enable_points" boolean DEFAULT true,
    "points_value" bigint DEFAULT 1000,
    "points_base_type" "text" DEFAULT '10000'::"text",
    "points_base_custom" bigint DEFAULT 5000,
    "points_earn_rate" bigint DEFAULT 1,
    "max_points_per_transaction" bigint DEFAULT 1000,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."point_settings" OWNER TO "postgres";


ALTER TABLE "public"."point_settings" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."point_settings_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."products" (
    "id" bigint NOT NULL,
    "name" character varying(255) NOT NULL,
    "price" numeric(12,2) NOT NULL,
    "category_id" bigint,
    "is_active" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "image_url" "text",
    "owner_id" "uuid",
    "outlet_id" bigint,
    "allowed_outlets" "jsonb" DEFAULT '["all"]'::"jsonb",
    "outlet_prices" "jsonb" DEFAULT '{}'::"jsonb"
);


ALTER TABLE "public"."products" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."products_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."products_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."products_id_seq" OWNED BY "public"."products"."id";



CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "name" "text",
    "email" "text",
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."promo_sent_logs" (
    "id" bigint NOT NULL,
    "customer_id" bigint NOT NULL,
    "template_id" bigint,
    "owner_id" "text",
    "sent_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."promo_sent_logs" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."promo_sent_logs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."promo_sent_logs_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."promo_sent_logs_id_seq" OWNED BY "public"."promo_sent_logs"."id";



CREATE TABLE IF NOT EXISTS "public"."promo_templates" (
    "id" integer NOT NULL,
    "name" "text" NOT NULL,
    "content" "text" NOT NULL,
    "owner_id" "text",
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."promo_templates" OWNER TO "postgres";


COMMENT ON TABLE "public"."promo_templates" IS 'Promo message templates accessible by everyone';



CREATE SEQUENCE IF NOT EXISTS "public"."promo_templates_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."promo_templates_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."promo_templates_id_seq" OWNED BY "public"."promo_templates"."id";



CREATE TABLE IF NOT EXISTS "public"."staff" (
    "id" bigint NOT NULL,
    "name" character varying(255) NOT NULL,
    "email" character varying(255) NOT NULL,
    "phone" character varying(50),
    "role" character varying(50) NOT NULL,
    "status" character varying(50) DEFAULT 'active'::character varying,
    "outlet_id" bigint,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "avatar_url" "text",
    "owner_id" "uuid"
);


ALTER TABLE "public"."staff" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."staff_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."staff_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."staff_id_seq" OWNED BY "public"."staff"."id";



CREATE TABLE IF NOT EXISTS "public"."transaction_items" (
    "id" bigint NOT NULL,
    "transaction_id" bigint NOT NULL,
    "product_id" bigint NOT NULL,
    "product_name" character varying(255) NOT NULL,
    "quantity" integer NOT NULL,
    "price" numeric(12,2) NOT NULL,
    "subtotal" numeric(12,2) NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "owner_id" "uuid"
);


ALTER TABLE "public"."transaction_items" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."transaction_items_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."transaction_items_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."transaction_items_id_seq" OWNED BY "public"."transaction_items"."id";



CREATE TABLE IF NOT EXISTS "public"."transactions" (
    "id" bigint NOT NULL,
    "customer_id" bigint,
    "cashier_name" character varying(255),
    "payment_method" character varying(50) NOT NULL,
    "subtotal" numeric(12,2) NOT NULL,
    "tax" numeric(12,2) NOT NULL,
    "discount" numeric(12,2) DEFAULT 0,
    "amount_paid" numeric(12,2) NOT NULL,
    "change" numeric(12,2) DEFAULT 0,
    "points_used" integer DEFAULT 0,
    "points_earned" integer DEFAULT 0,
    "status" character varying(50) DEFAULT 'completed'::character varying,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "discount_note" character varying(255),
    "customer_type" character varying(50) DEFAULT 'non_member'::character varying,
    "owner_id" "uuid",
    "outlet_id" bigint
);


ALTER TABLE "public"."transactions" OWNER TO "postgres";


COMMENT ON COLUMN "public"."transactions"."discount_note" IS 'Keterangan atau alasan diskon pada transaksi';



COMMENT ON COLUMN "public"."transactions"."customer_type" IS 'Tipe pelanggan saat transaksi: member atau non_member';



CREATE SEQUENCE IF NOT EXISTS "public"."transactions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."transactions_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."transactions_id_seq" OWNED BY "public"."transactions"."id";



ALTER TABLE ONLY "public"."app_config" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."app_config_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."categories" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."categories_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."customers" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."customers_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."outlets" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."outlets_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."products" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."products_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."promo_sent_logs" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."promo_sent_logs_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."promo_templates" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."promo_templates_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."staff" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."staff_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."transaction_items" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."transaction_items_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."transactions" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."transactions_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."app_config"
    ADD CONSTRAINT "app_config_key_key" UNIQUE ("key");



ALTER TABLE ONLY "public"."app_config"
    ADD CONSTRAINT "app_config_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."categories"
    ADD CONSTRAINT "categories_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."customers"
    ADD CONSTRAINT "customers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."discount_categories"
    ADD CONSTRAINT "discount_categories_note_key" UNIQUE ("note");



ALTER TABLE ONLY "public"."discount_categories"
    ADD CONSTRAINT "discount_categories_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."discount_settings"
    ADD CONSTRAINT "discount_settings_outlet_id_staff_email_key" UNIQUE ("outlet_id", "staff_email");



ALTER TABLE ONLY "public"."discount_settings"
    ADD CONSTRAINT "discount_settings_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."expense_categories"
    ADD CONSTRAINT "expense_categories_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."expenses"
    ADD CONSTRAINT "expenses_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."outlets"
    ADD CONSTRAINT "outlets_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."point_settings"
    ADD CONSTRAINT "point_settings_outlet_id_staff_email_key" UNIQUE ("outlet_id", "staff_email");



ALTER TABLE ONLY "public"."point_settings"
    ADD CONSTRAINT "point_settings_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."products"
    ADD CONSTRAINT "products_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."promo_sent_logs"
    ADD CONSTRAINT "promo_sent_logs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."promo_templates"
    ADD CONSTRAINT "promo_templates_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."staff"
    ADD CONSTRAINT "staff_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."transaction_items"
    ADD CONSTRAINT "transaction_items_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."transactions"
    ADD CONSTRAINT "transactions_pkey" PRIMARY KEY ("id");



CREATE INDEX "idx_categories_owner" ON "public"."categories" USING "btree" ("owner_id");



CREATE INDEX "idx_customers_owner" ON "public"."customers" USING "btree" ("owner_id");



CREATE UNIQUE INDEX "idx_discount_settings_unique_target" ON "public"."discount_settings" USING "btree" (COALESCE("outlet_id", ('-1'::integer)::bigint), COALESCE("staff_email", 'ALL_STAFF'::"text"));



CREATE INDEX "idx_expenses_outlet_id" ON "public"."expenses" USING "btree" ("outlet_id");



CREATE INDEX "idx_expenses_owner_id" ON "public"."expenses" USING "btree" ("owner_id");



CREATE INDEX "idx_outlets_is_active" ON "public"."outlets" USING "btree" ("is_active");



CREATE UNIQUE INDEX "idx_point_settings_unique_target" ON "public"."point_settings" USING "btree" (COALESCE("outlet_id", ('-1'::integer)::bigint), COALESCE("staff_email", 'ALL_STAFF'::"text"));



CREATE INDEX "idx_products_category_id" ON "public"."products" USING "btree" ("category_id");



CREATE INDEX "idx_products_is_active" ON "public"."products" USING "btree" ("is_active");



CREATE INDEX "idx_products_outlet_id" ON "public"."products" USING "btree" ("outlet_id");



CREATE INDEX "idx_products_owner" ON "public"."products" USING "btree" ("owner_id");



CREATE INDEX "idx_staff_owner_id" ON "public"."staff" USING "btree" ("owner_id");



CREATE INDEX "idx_transaction_items_owner" ON "public"."transaction_items" USING "btree" ("owner_id");



CREATE INDEX "idx_transaction_items_product_id" ON "public"."transaction_items" USING "btree" ("product_id");



CREATE INDEX "idx_transaction_items_transaction_id" ON "public"."transaction_items" USING "btree" ("transaction_id");



CREATE INDEX "idx_transactions_created_at" ON "public"."transactions" USING "btree" ("created_at");



CREATE INDEX "idx_transactions_customer_id" ON "public"."transactions" USING "btree" ("customer_id");



CREATE INDEX "idx_transactions_outlet_id" ON "public"."transactions" USING "btree" ("outlet_id");



CREATE INDEX "idx_transactions_owner" ON "public"."transactions" USING "btree" ("owner_id");



CREATE OR REPLACE TRIGGER "update_categories_updated_at" BEFORE UPDATE ON "public"."categories" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



CREATE OR REPLACE TRIGGER "update_customers_updated_at" BEFORE UPDATE ON "public"."customers" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



CREATE OR REPLACE TRIGGER "update_outlets_updated_at" BEFORE UPDATE ON "public"."outlets" FOR EACH ROW EXECUTE FUNCTION "public"."update_outlets_updated_at"();



CREATE OR REPLACE TRIGGER "update_products_updated_at" BEFORE UPDATE ON "public"."products" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



ALTER TABLE ONLY "public"."customers"
    ADD CONSTRAINT "customers_outlet_id_fkey" FOREIGN KEY ("outlet_id") REFERENCES "public"."outlets"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."discount_settings"
    ADD CONSTRAINT "discount_settings_outlet_id_fkey" FOREIGN KEY ("outlet_id") REFERENCES "public"."outlets"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."products"
    ADD CONSTRAINT "fk_products_outlet" FOREIGN KEY ("outlet_id") REFERENCES "public"."outlets"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."point_settings"
    ADD CONSTRAINT "point_settings_outlet_id_fkey" FOREIGN KEY ("outlet_id") REFERENCES "public"."outlets"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."products"
    ADD CONSTRAINT "products_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."staff"
    ADD CONSTRAINT "staff_outlet_id_fkey" FOREIGN KEY ("outlet_id") REFERENCES "public"."outlets"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."transaction_items"
    ADD CONSTRAINT "transaction_items_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."transaction_items"
    ADD CONSTRAINT "transaction_items_transaction_id_fkey" FOREIGN KEY ("transaction_id") REFERENCES "public"."transactions"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."transactions"
    ADD CONSTRAINT "transactions_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."transactions"
    ADD CONSTRAINT "transactions_outlet_id_fkey" FOREIGN KEY ("outlet_id") REFERENCES "public"."outlets"("id") ON DELETE SET NULL;



CREATE POLICY "Admin can view all profiles" ON "public"."profiles" FOR SELECT USING ((("auth"."email"() = 'sbagiamu.pos@gmail.com'::"text") OR ("auth"."uid"() = "id")));



CREATE POLICY "Allow public delete on categories" ON "public"."categories" FOR DELETE USING (true);



CREATE POLICY "Allow public delete on customers" ON "public"."customers" FOR DELETE USING (true);



CREATE POLICY "Allow public delete on expense_categories" ON "public"."expense_categories" FOR DELETE USING (true);



CREATE POLICY "Allow public delete on outlets" ON "public"."outlets" FOR DELETE USING (true);



CREATE POLICY "Allow public delete on products" ON "public"."products" FOR DELETE USING (true);



CREATE POLICY "Allow public delete on transaction_items" ON "public"."transaction_items" FOR DELETE USING (true);



CREATE POLICY "Allow public delete on transactions" ON "public"."transactions" FOR DELETE USING (true);



CREATE POLICY "Allow public insert on categories" ON "public"."categories" FOR INSERT WITH CHECK (true);



CREATE POLICY "Allow public insert on customers" ON "public"."customers" FOR INSERT WITH CHECK (true);



CREATE POLICY "Allow public insert on expense_categories" ON "public"."expense_categories" FOR INSERT WITH CHECK (true);



CREATE POLICY "Allow public insert on outlets" ON "public"."outlets" FOR INSERT WITH CHECK (true);



CREATE POLICY "Allow public insert on products" ON "public"."products" FOR INSERT WITH CHECK (true);



CREATE POLICY "Allow public insert on transaction_items" ON "public"."transaction_items" FOR INSERT WITH CHECK (true);



CREATE POLICY "Allow public insert on transactions" ON "public"."transactions" FOR INSERT WITH CHECK (true);



CREATE POLICY "Allow public read on categories" ON "public"."categories" FOR SELECT USING (true);



CREATE POLICY "Allow public read on customers" ON "public"."customers" FOR SELECT USING (true);



CREATE POLICY "Allow public read on expense_categories" ON "public"."expense_categories" FOR SELECT USING (true);



CREATE POLICY "Allow public read on outlets" ON "public"."outlets" FOR SELECT USING (true);



CREATE POLICY "Allow public read on products" ON "public"."products" FOR SELECT USING (true);



CREATE POLICY "Allow public read on transaction_items" ON "public"."transaction_items" FOR SELECT USING (true);



CREATE POLICY "Allow public read on transactions" ON "public"."transactions" FOR SELECT USING (true);



CREATE POLICY "Allow public read on transactions_by_outlet" ON "public"."transactions" FOR SELECT USING (true);



CREATE POLICY "Allow public update on categories" ON "public"."categories" FOR UPDATE USING (true);



CREATE POLICY "Allow public update on customers" ON "public"."customers" FOR UPDATE USING (true);



CREATE POLICY "Allow public update on expense_categories" ON "public"."expense_categories" FOR UPDATE USING (true);



CREATE POLICY "Allow public update on outlets" ON "public"."outlets" FOR UPDATE USING (true);



CREATE POLICY "Allow public update on products" ON "public"."products" FOR UPDATE USING (true);



CREATE POLICY "Allow public update on transaction_items" ON "public"."transaction_items" FOR UPDATE USING (true) WITH CHECK (true);



CREATE POLICY "Allow public update on transactions" ON "public"."transactions" FOR UPDATE USING (true) WITH CHECK (true);



CREATE POLICY "Allow read for all" ON "public"."app_config" FOR SELECT USING (true);



CREATE POLICY "Allow update products" ON "public"."products" FOR UPDATE USING (true) WITH CHECK (true);



CREATE POLICY "Enable delete for authenticated users" ON "public"."point_settings" FOR DELETE USING (true);



CREATE POLICY "Enable delete for authenticated users on discount_categories" ON "public"."discount_categories" FOR DELETE USING (true);



CREATE POLICY "Enable delete for authenticated users on discount_settings" ON "public"."discount_settings" FOR DELETE USING (true);



CREATE POLICY "Enable delete for owner" ON "public"."promo_sent_logs" FOR DELETE USING (true);



CREATE POLICY "Enable insert for authenticated users" ON "public"."point_settings" FOR INSERT WITH CHECK (true);



CREATE POLICY "Enable insert for authenticated users" ON "public"."promo_sent_logs" FOR INSERT WITH CHECK (true);



CREATE POLICY "Enable insert for authenticated users" ON "public"."promo_templates" FOR INSERT WITH CHECK (true);



CREATE POLICY "Enable insert for authenticated users on discount_categories" ON "public"."discount_categories" FOR INSERT WITH CHECK (true);



CREATE POLICY "Enable insert for authenticated users on discount_settings" ON "public"."discount_settings" FOR INSERT WITH CHECK (true);



CREATE POLICY "Enable read access for all users" ON "public"."point_settings" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users on discount_categories" ON "public"."discount_categories" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users on discount_settings" ON "public"."discount_settings" FOR SELECT USING (true);



CREATE POLICY "Enable read access for authenticated users" ON "public"."promo_sent_logs" FOR SELECT USING (true);



CREATE POLICY "Enable read access for authenticated users" ON "public"."promo_templates" FOR SELECT USING (true);



CREATE POLICY "Enable update for authenticated users" ON "public"."point_settings" FOR UPDATE USING (true);



CREATE POLICY "Enable update for authenticated users on discount_categories" ON "public"."discount_categories" FOR UPDATE USING (true);



CREATE POLICY "Enable update for authenticated users on discount_settings" ON "public"."discount_settings" FOR UPDATE USING (true);



CREATE POLICY "Enable update/delete for owner" ON "public"."promo_templates" USING (true) WITH CHECK (true);



CREATE POLICY "Users can view own profile" ON "public"."profiles" FOR SELECT USING (("auth"."uid"() = "id"));



ALTER TABLE "public"."app_config" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."categories" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."customers" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."discount_categories" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."discount_settings" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."expense_categories" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."expenses" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "expenses_delete" ON "public"."expenses" FOR DELETE USING ((("owner_id" = "auth"."uid"()) OR ("auth"."uid"() IS NULL)));



CREATE POLICY "expenses_insert" ON "public"."expenses" FOR INSERT WITH CHECK ((("owner_id" = "auth"."uid"()) OR ("auth"."uid"() IS NULL)));



CREATE POLICY "expenses_select" ON "public"."expenses" FOR SELECT USING ((("owner_id" = "auth"."uid"()) OR ("owner_id" IS NULL) OR ("auth"."uid"() IS NULL)));



CREATE POLICY "expenses_update" ON "public"."expenses" FOR UPDATE USING ((("owner_id" = "auth"."uid"()) OR ("owner_id" IS NULL) OR ("auth"."uid"() IS NULL)));



ALTER TABLE "public"."outlets" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."point_settings" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."products" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."promo_sent_logs" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."promo_templates" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."staff" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "staff_public_delete" ON "public"."staff" FOR DELETE USING (true);



CREATE POLICY "staff_public_insert" ON "public"."staff" FOR INSERT WITH CHECK (true);



CREATE POLICY "staff_public_select" ON "public"."staff" FOR SELECT USING (true);



CREATE POLICY "staff_public_update" ON "public"."staff" FOR UPDATE USING (true);



ALTER TABLE "public"."transaction_items" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."transactions" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";






ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."categories";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."customers";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."expense_categories";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."expenses";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."outlets";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."point_settings";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."products";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."promo_sent_logs";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."promo_templates";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."staff";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."transaction_items";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."transactions";



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";






















































































































































GRANT ALL ON FUNCTION "public"."is_admin"() TO "authenticated";



GRANT ALL ON FUNCTION "public"."set_owner_id"() TO "authenticated";


















GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."app_config" TO "anon";
GRANT SELECT,REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."app_config" TO "authenticated";
GRANT ALL ON TABLE "public"."app_config" TO "service_role";



GRANT ALL ON TABLE "public"."categories" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."categories" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."categories" TO "service_role";



GRANT ALL ON SEQUENCE "public"."categories_id_seq" TO "anon";
GRANT SELECT,USAGE ON SEQUENCE "public"."categories_id_seq" TO "authenticated";



GRANT ALL ON TABLE "public"."customers" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."customers" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."customers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."customers_id_seq" TO "anon";
GRANT SELECT,USAGE ON SEQUENCE "public"."customers_id_seq" TO "authenticated";



GRANT ALL ON TABLE "public"."discount_categories" TO "anon";
GRANT ALL ON TABLE "public"."discount_categories" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."discount_categories" TO "service_role";



GRANT ALL ON SEQUENCE "public"."discount_categories_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."discount_categories_id_seq" TO "authenticated";



GRANT ALL ON TABLE "public"."discount_settings" TO "anon";
GRANT ALL ON TABLE "public"."discount_settings" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."discount_settings" TO "service_role";



GRANT ALL ON SEQUENCE "public"."discount_settings_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."discount_settings_id_seq" TO "authenticated";



GRANT ALL ON TABLE "public"."expense_categories" TO "anon";
GRANT ALL ON TABLE "public"."expense_categories" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."expense_categories" TO "service_role";



GRANT ALL ON TABLE "public"."expenses" TO "anon";
GRANT ALL ON TABLE "public"."expenses" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."expenses" TO "service_role";



GRANT SELECT,USAGE ON SEQUENCE "public"."expenses_id_seq" TO "anon";
GRANT SELECT,USAGE ON SEQUENCE "public"."expenses_id_seq" TO "authenticated";



GRANT ALL ON TABLE "public"."outlets" TO "anon";
GRANT ALL ON TABLE "public"."outlets" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."outlets" TO "service_role";



GRANT SELECT,USAGE ON SEQUENCE "public"."outlets_id_seq" TO "anon";
GRANT SELECT,USAGE ON SEQUENCE "public"."outlets_id_seq" TO "authenticated";



GRANT ALL ON TABLE "public"."point_settings" TO "anon";
GRANT ALL ON TABLE "public"."point_settings" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."point_settings" TO "service_role";



GRANT ALL ON SEQUENCE "public"."point_settings_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."point_settings_id_seq" TO "authenticated";



GRANT ALL ON TABLE "public"."products" TO "anon";
GRANT ALL ON TABLE "public"."products" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."products" TO "service_role";



GRANT ALL ON SEQUENCE "public"."products_id_seq" TO "anon";
GRANT SELECT,USAGE ON SEQUENCE "public"."products_id_seq" TO "authenticated";



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."profiles" TO "service_role";



GRANT ALL ON TABLE "public"."promo_sent_logs" TO "anon";
GRANT ALL ON TABLE "public"."promo_sent_logs" TO "authenticated";
GRANT ALL ON TABLE "public"."promo_sent_logs" TO "service_role";
GRANT ALL ON TABLE "public"."promo_sent_logs" TO PUBLIC;



GRANT ALL ON SEQUENCE "public"."promo_sent_logs_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."promo_sent_logs_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."promo_sent_logs_id_seq" TO "service_role";
GRANT ALL ON SEQUENCE "public"."promo_sent_logs_id_seq" TO PUBLIC;



GRANT ALL ON TABLE "public"."promo_templates" TO "anon";
GRANT ALL ON TABLE "public"."promo_templates" TO "authenticated";
GRANT ALL ON TABLE "public"."promo_templates" TO "service_role";
GRANT ALL ON TABLE "public"."promo_templates" TO PUBLIC;



GRANT ALL ON SEQUENCE "public"."promo_templates_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."promo_templates_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."promo_templates_id_seq" TO "service_role";
GRANT ALL ON SEQUENCE "public"."promo_templates_id_seq" TO PUBLIC;



GRANT ALL ON TABLE "public"."staff" TO "anon";
GRANT ALL ON TABLE "public"."staff" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."staff" TO "service_role";



GRANT SELECT,USAGE ON SEQUENCE "public"."staff_id_seq" TO "anon";
GRANT SELECT,USAGE ON SEQUENCE "public"."staff_id_seq" TO "authenticated";



GRANT ALL ON TABLE "public"."transaction_items" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."transaction_items" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."transaction_items" TO "service_role";



GRANT ALL ON SEQUENCE "public"."transaction_items_id_seq" TO "anon";
GRANT SELECT,USAGE ON SEQUENCE "public"."transaction_items_id_seq" TO "authenticated";



GRANT ALL ON TABLE "public"."transactions" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."transactions" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."transactions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."transactions_id_seq" TO "anon";
GRANT SELECT,USAGE ON SEQUENCE "public"."transactions_id_seq" TO "authenticated";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO "service_role";































